// Date: 4/6/2013 4:10:13 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package wildycraft.client.model;

import org.lwjgl.opengl.GL11;

import wildycraft.entity.EntityPackYak;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelPackYak extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer horn1;
    ModelRenderer horn2;
    ModelRenderer snout;
    ModelRenderer fur;
    ModelRenderer pack;
    ModelRenderer white_stripe;
    ModelRenderer pack2;
    ModelRenderer rope;
  
  public ModelPackYak()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      head = new ModelRenderer(this, 3, 52);
      head.addBox(-4F, -5F, -3F, 8, 6, 6);
      head.setRotationPoint(0F, 6F, -8F);
      head.setTextureSize(128, 128);
      head.mirror = true;
      setRotation(head, 0.4348865F, 0F, 0F);
      body = new ModelRenderer(this, 41, 87);
      body.addBox(-6F, -10F, -9F, 12, 28, 12);
      body.setRotationPoint(0F, 5F, 2F);
      body.setTextureSize(128, 128);
      body.mirror = true;
      setRotation(body, 1.570796F, 0F, 0F);
      leg1 = new ModelRenderer(this, 17, 102);
      leg1.addBox(-2F, 0F, -2F, 4, 12, 4);
      leg1.setRotationPoint(-4F, 12F, 16F);
      leg1.setTextureSize(128, 128);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 17, 102);
      leg2.addBox(-2F, 0F, -2F, 4, 12, 4);
      leg2.setRotationPoint(4F, 12F, 16F);
      leg2.setTextureSize(128, 128);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 17, 102);
      leg3.addBox(-2F, 0F, -2F, 4, 12, 4);
      leg3.setRotationPoint(-4F, 12F, -5F);
      leg3.setTextureSize(128, 128);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 17, 102);
      leg4.addBox(-2F, 0F, -2F, 4, 12, 4);
      leg4.setRotationPoint(4F, 12F, -5F);
      leg4.setTextureSize(128, 128);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      horn1 = new ModelRenderer(this, 20, 34);
      horn1.addBox(-4F, -13F, 1.5F, 2, 10, 2);
      horn1.setRotationPoint(0F, 5F, -7F);
      horn1.setTextureSize(128, 128);
      horn1.mirror = true;
      setRotation(horn1, 1.466077F, 0F, 0F);
      horn2 = new ModelRenderer(this, 20, 34);
      horn2.addBox(2F, -13F, 1.5F, 2, 10, 2);
      horn2.setRotationPoint(0F, 5F, -7F);
      horn2.setTextureSize(128, 128);
      horn2.mirror = true;
      setRotation(horn2, 1.466077F, 0F, 0F);
      snout = new ModelRenderer(this, 4, 69);
      snout.addBox(-2F, 0F, -2F, 4, 7, 3);
      snout.setRotationPoint(0F, 6F, -8F);
      snout.setTextureSize(128, 128);
      snout.mirror = true;
      setRotation(snout, -1.13591F, 0F, 0F);
      fur = new ModelRenderer(this, 33, 41);
      fur.addBox(-8F, -4F, -9F, 16, 14, 25);
      fur.setRotationPoint(0F, 5F, 2F);
      fur.setTextureSize(128, 128);
      fur.mirror = true;
      setRotation(fur, 0F, 0F, 0F);
      pack = new ModelRenderer(this, 51, 0);
      pack.addBox(-12F, -3F, 2F, 5, 8, 8);
      pack.setRotationPoint(0F, 5F, 2F);
      pack.setTextureSize(128, 128);
      pack.mirror = true;
      setRotation(pack, -0.1487144F, 0.1942582F, 0.3346075F);
      white_stripe = new ModelRenderer(this, 0, 0);
      white_stripe.addBox(-4F, -6F, -8F, 8, 4, 17);
      white_stripe.setRotationPoint(0F, 5F, 2F);
      white_stripe.setTextureSize(128, 128);
      white_stripe.mirror = true;
      setRotation(white_stripe, 0F, 0F, 0F);
      pack2 = new ModelRenderer(this, 77, 0);
      pack2.addBox(-11F, -2F, -10F, 5, 8, 8);
      pack2.setRotationPoint(0F, 5F, 2F);
      pack2.setTextureSize(128, 128);
      pack2.mirror = true;
      setRotation(pack2, 0.0743572F, 3.085825F, 0.4461433F);
      rope = new ModelRenderer(this, 51, 18);
      rope.addBox(-7F, -5F, 9F, 13, 1, 1);
      rope.setRotationPoint(0F, 5F, 2F);
      rope.setTextureSize(128, 128);
      rope.mirror = true;
      setRotation(rope, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    //super.render(entity, f, f1, f2, f3, f4, f5);
	  setRotationAngles(f, f1, f2, f3, f4, f5,entity);
	  if (((EntityPackYak)entity).isSitting())
      {
		  GL11.glPushMatrix();
	            GL11.glTranslatef(0.0F, 8.0F * f5, 0.0F);
	            head.renderWithRotation(f5);
	            body.renderWithRotation(f5);
	            //leg1.renderWithRotation(f5);
	            //leg2.renderWithRotation(f5);
	            //leg3.renderWithRotation(f5);
	            //leg4.renderWithRotation(f5);
	            horn1.renderWithRotation(f5);
	            horn2.renderWithRotation(f5);
	            snout.renderWithRotation(f5);
	            fur.renderWithRotation(f5);
	            pack.renderWithRotation(f5);
	            white_stripe.renderWithRotation(f5);
	            pack2.renderWithRotation(f5);
    	rope.renderWithRotation(f5);
    	GL11.glPopMatrix();
      } else{
    	  head.renderWithRotation(f5);
    	    body.renderWithRotation(f5);
    	    leg1.renderWithRotation(f5);
    	    leg2.renderWithRotation(f5);
    	    leg3.renderWithRotation(f5);
    	    leg4.renderWithRotation(f5);
    	    horn1.renderWithRotation(f5);
    	    horn2.renderWithRotation(f5);
    	    snout.renderWithRotation(f5);
    	    fur.renderWithRotation(f5);
    	    pack.renderWithRotation(f5);
    	    white_stripe.renderWithRotation(f5);
    	    pack2.renderWithRotation(f5);
    	    rope.renderWithRotation(f5);
      }
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6,Entity entity)
  {
    super.setRotationAngles(par1, par2, par3, par4, par5, par6,entity);
    this.head.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.head.rotateAngleY = par4 / (180F / (float)Math.PI);
    horn1.rotateAngleX = head.rotateAngleX + 1.0311905F;
    horn1.rotateAngleY = head.rotateAngleY;
    horn2.rotateAngleX = head.rotateAngleX + 1.0311905F;
    horn2.rotateAngleY = head.rotateAngleY;
    snout.rotateAngleX = head.rotateAngleX -1.57079F;
    snout.rotateAngleY = head.rotateAngleY;
    this.body.rotateAngleX = ((float)Math.PI / 2F);
    this.leg1.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
    this.leg2.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
    this.leg3.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
    this.leg4.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
  }

}
