// Date: 3/23/2013 6:53:50 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package wildycraft.client.model;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelTopHat extends ModelBiped
{
    public ModelRenderer Shape1;
    ModelRenderer Shape2;
  
  public ModelTopHat(float f)
  {
	  super(f);
	  textureWidth = 64;
	  textureHeight = 64;
    
      bipedHead = new ModelRenderer(this, 1,34);
      bipedHead.setRotationPoint(0.0F, 0.0F, 0.0F);
      bipedHead.setTextureSize(64, 64);
      bipedHead.mirror = true;
      setRotation(bipedHead, 0F, 0F, 0F);
      bipedBody = new ModelRenderer(this, 12, 34);
      bipedBody.addBox(-4F, 0F, -2F, 8, 12, 4);
      bipedBody.setRotationPoint(0F, 6F, 0F);
      bipedBody.setTextureSize(64, 64);
      bipedBody.mirror = true;
      setRotation(bipedBody, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 22);
      Shape1.addBox(-5F, -9F, -5F, 10, 1, 10);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(64, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      this.bipedHead.addChild(Shape1);
      Shape2 = new ModelRenderer(this, 36, 0);
      Shape2.addBox(-3F, -12F, -4F, 6, 3, 8);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(64, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      this.bipedHead.addChild(Shape2);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  /*public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
      this.bipedHead.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.bipedHead.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Shape1.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Shape1.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Shape2.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Shape2.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.leg1.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
      this.leg2.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
      this.leg3.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
      this.leg4.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
  }*/

}
