// Date: 3/26/2013 8:00:19 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX



package wildycraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelDagannoth extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
  
  public ModelDagannoth()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 24, 0);
      head.addBox(-4F, -8F, -1F, 7, 6, 5);
      head.setRotationPoint(-0.5F, 2F, -3.5F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 3.141593F, 0F);
      body = new ModelRenderer(this, 14, 17);
      body.addBox(-4F, 0F, -2F, 8, 14, 4);
      body.setRotationPoint(0F, 0F, -4F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, -0.5585054F, 3.141593F, 0F);
      rightarm = new ModelRenderer(this, 1, 24);
      rightarm.addBox(0F, -2F, -2F, 3, 10, 3);
      rightarm.setRotationPoint(-4F, 2F, -4F);
      rightarm.setTextureSize(64, 64);
      rightarm.mirror = true;
      setRotation(rightarm, -0.0349066F, -3.141593F, 0F);
      leftarm = new ModelRenderer(this, 1, 24);
      leftarm.addBox(-1F, -2F, -2F, 3, 10, 3);
      leftarm.setRotationPoint(6F, 2F, -4F);
      leftarm.setTextureSize(64, 64);
      leftarm.mirror = true;
      setRotation(leftarm, -0.0349066F, 3.141593F, 0F);
      rightleg = new ModelRenderer(this, 24, 37);
      rightleg.addBox(-2F, 0F, -2F, 3, 7, 4);
      rightleg.setRotationPoint(-3F, 12F, 2F);
      rightleg.setTextureSize(64, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0.8726646F, 3.141593F, 0F);
      leftleg = new ModelRenderer(this, 24, 37);
      leftleg.addBox(-2F, 0F, -2F, 3, 7, 4);
      leftleg.setRotationPoint(3F, 12F, 2F);
      leftleg.setTextureSize(64, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0.8726646F, 3.141593F, 0F);
      Shape1 = new ModelRenderer(this, 44, 34);
      Shape1.addBox(-0.5F, 13F, -0.5F, 3, 1, 1);
      Shape1.setRotationPoint(0F, 0F, -4F);
      Shape1.setTextureSize(64, 64);
      Shape1.mirror = true;
      setRotation(Shape1, -0.0174533F, -1.628836F, -0.7330383F);
      Shape2 = new ModelRenderer(this, 25, 51);
      Shape2.addBox(-2F, -6F, 0F, 3, 3, 9);
      Shape2.setRotationPoint(3F, 13F, 2F);
      Shape2.setTextureSize(64, 64);
      Shape2.mirror = true;
      setRotation(Shape2, -2.181662F, 3.141593F, 0F);
      Shape3 = new ModelRenderer(this, 25, 51);
      Shape3.addBox(-2F, -7F, 0F, 3, 3, 9);
      Shape3.setRotationPoint(-3F, 12F, 2F);
      Shape3.setTextureSize(64, 64);
      Shape3.mirror = true;
      setRotation(Shape3, -2.181662F, 3.141593F, 0F);
      Shape4 = new ModelRenderer(this, 1, 2);
      Shape4.addBox(-2.5F, -6F, 4F, 4, 4, 5);
      Shape4.setRotationPoint(-0.5F, 2F, -3.5F);
      Shape4.setTextureSize(64, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 3.141593F, 0F);
      Shape5 = new ModelRenderer(this, 2, 53);
      Shape5.addBox(-3F, 11F, 0F, 5, 1, 5);
      Shape5.setRotationPoint(3F, 12F, 2F);
      Shape5.setTextureSize(64, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 3.141593F, 0F);
      Shape6 = new ModelRenderer(this, 2, 53);
      Shape6.addBox(-3F, 11F, 0F, 5, 1, 5);
      Shape6.setRotationPoint(-3F, 12F, 2F);
      Shape6.setTextureSize(64, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 3.141593F, 0F);
      Shape7 = new ModelRenderer(this, 39, 22);
      Shape7.addBox(0F, 0F, 0F, 3, 1, 10);
      Shape7.setRotationPoint(1.5F, 7F, 3.666667F);
      Shape7.setTextureSize(64, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 1.012291F, 3.141593F, 0F);
      Shape8 = new ModelRenderer(this, 45, 14);
      Shape8.addBox(0F, 2F, -6F, 0, 5, 1);
      Shape8.setRotationPoint(0F, 0F, -4F);
      Shape8.setTextureSize(64, 64);
      Shape8.mirror = true;
      setRotation(Shape8, 2.164828F, -0.0154911F, 0F);
      Shape9 = new ModelRenderer(this, 52, 10);
      Shape9.addBox(0F, 2F, -4F, 0, 8, 1);
      Shape9.setRotationPoint(0F, 0F, -4F);
      Shape9.setTextureSize(64, 64);
      Shape9.mirror = true;
      setRotation(Shape9, 2.155327F, 0.0174533F, 0F);
      Shape10 = new ModelRenderer(this, 59, 13);
      Shape10.addBox(0F, 2F, 1F, 0, 5, 1);
      Shape10.setRotationPoint(0F, 0F, -4F);
      Shape10.setTextureSize(64, 64);
      Shape10.mirror = true;
      setRotation(Shape10, -2.146755F, 3.141593F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    //super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    head.renderWithRotation(f5);
    body.renderWithRotation(f5);
    rightarm.renderWithRotation(f5);
    leftarm.renderWithRotation(f5);
    rightleg.renderWithRotation(f5);
    leftleg.renderWithRotation(f5);
    Shape1.renderWithRotation(f5);
    Shape2.renderWithRotation(f5);
    Shape3.renderWithRotation(f5);
    Shape4.renderWithRotation(f5);
    Shape5.renderWithRotation(f5);
    Shape6.renderWithRotation(f5);
    Shape7.renderWithRotation(f5);
    Shape8.renderWithRotation(f5);
    Shape9.renderWithRotation(f5);
    Shape10.renderWithRotation(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6,Entity entity)
  {
    super.setRotationAngles(par1, par2, par3, par4, par5, par6,entity);
    this.head.rotateAngleY = -3.1415926F + par4 / (180F / (float)Math.PI);
    this.head.rotateAngleX = -par5 / (180F / (float)Math.PI);
    this.Shape4.rotateAngleY = this.head.rotateAngleY;
    this.Shape4.rotateAngleX = this.head.rotateAngleX;
    this.rightarm.rotateAngleX = 3.1415926F/6;
    this.leftarm.rotateAngleX = 3.1415926F/6;
    this.rightleg.rotateAngleX = 0.8726646F + MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
    this.leftleg.rotateAngleX = 0.8726646F + MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
    this.rightleg.rotateAngleY = 3.141593F;
    this.leftleg.rotateAngleY = 3.141593F;
    this.Shape2.rotateAngleY = this.leftleg.rotateAngleY;
    this.Shape2.rotateAngleX = -2.181662F - 0.8726646F+ this.leftleg.rotateAngleX;
    this.Shape5.rotateAngleY = this.leftleg.rotateAngleY;
    this.Shape5.rotateAngleX = -0.8726646F + this.leftleg.rotateAngleX;
    this.Shape3.rotateAngleY = this.rightleg.rotateAngleY;
    this.Shape3.rotateAngleX = -2.181662F - 0.8726646F+ this.rightleg.rotateAngleX;
    this.Shape6.rotateAngleY = this.rightleg.rotateAngleY;
    this.Shape6.rotateAngleX = -0.8726646F + this.rightleg.rotateAngleX;
  }

}
