// Date: 3/27/2013 12:21:45 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package wildycraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelAbyssalDemon extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer middle;
    ModelRenderer neck;
    ModelRenderer back_of_head;
    ModelRenderer segment_1;
    ModelRenderer segment_2;
    ModelRenderer Segment_3;
    ModelRenderer segment_4;
    ModelRenderer foot_3;
    ModelRenderer foot_4;
    ModelRenderer arm_1;
    ModelRenderer arm_2;
    ModelRenderer foot_1;
    ModelRenderer foot2;
    ModelRenderer hand_1;
    ModelRenderer Hand_2;
    ModelRenderer claw_1;
    ModelRenderer claw_2;
  
  public ModelAbyssalDemon()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 15, 0);
      head.addBox(-4F, -7F, -2F, 6, 5, 9);
      head.setRotationPoint(-1F, 5F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 3.141593F, 0F);
      body = new ModelRenderer(this, 29, 46);
      body.addBox(-4F, 0F, -2F, 8, 5, 9);
      body.setRotationPoint(0F, 13F, -3F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 19, 47);
      leg3.addBox(1F, -1F, -6F, 2, 10, 2);
      leg3.setRotationPoint(0F, 13F, -3F);
      leg3.setTextureSize(64, 64);
      leg3.mirror = true;
      setRotation(leg3, 2.408554F, -2.548181F, 0F);
      leg4 = new ModelRenderer(this, 19, 47);
      leg4.addBox(0F, -1F, 4F, 2, 10, 2);
      leg4.setRotationPoint(0F, 13F, -3F);
      leg4.setTextureSize(64, 64);
      leg4.mirror = true;
      setRotation(leg4, -2.408554F, -0.9075712F, 0F);
      leg1 = new ModelRenderer(this, 19, 47);
      leg1.addBox(1.5F, 1F, -8F, 2, 10, 2);
      leg1.setRotationPoint(0F, 13F, -3F);
      leg1.setTextureSize(64, 64);
      leg1.mirror = true;
      setRotation(leg1, 2.408554F, -0.8552113F, 0F);
      leg2 = new ModelRenderer(this, 19, 47);
      leg2.addBox(-1F, 1F, -8F, 2, 10, 2);
      leg2.setRotationPoint(0F, 13F, -3F);
      leg2.setTextureSize(64, 64);
      leg2.mirror = true;
      setRotation(leg2, 2.408554F, 0.5585054F, 0F);
      middle = new ModelRenderer(this, 24, 26);
      middle.addBox(-2F, -8F, 0F, 4, 8, 5);
      middle.setRotationPoint(0F, 13F, -3F);
      middle.setTextureSize(64, 64);
      middle.mirror = true;
      setRotation(middle, 0F, 0F, 0F);
      neck = new ModelRenderer(this, 27, 18);
      neck.addBox(0F, -3F, -2F, 2, 2, 3);
      neck.setRotationPoint(-1F, 6F, 0F);
      neck.setTextureSize(64, 64);
      neck.mirror = true;
      setRotation(neck, 0F, 0F, 0F);
      back_of_head = new ModelRenderer(this, 46, 0);
      back_of_head.addBox(-2F, -7F, 2F, 6, 1, 3);
      back_of_head.setRotationPoint(-1F, 5F, 0F);
      back_of_head.setTextureSize(64, 64);
      back_of_head.mirror = true;
      setRotation(back_of_head, 0F, 0F, 0F);
      segment_1 = new ModelRenderer(this, 9, 47);
      segment_1.addBox(-0.7F, 0F, -1F, 2, 12, 2);
      segment_1.setRotationPoint(-8F, 10F, 7F);
      segment_1.setTextureSize(64, 64);
      segment_1.mirror = true;
      setRotation(segment_1, 0F, -0.8552113F, 0F);
      segment_2 = new ModelRenderer(this, 9, 47);
      segment_2.addBox(-1F, 0F, 0F, 2, 12, 2);
      segment_2.setRotationPoint(6.4F, 10F, 7F);
      segment_2.setTextureSize(64, 64);
      segment_2.mirror = true;
      setRotation(segment_2, 0F, 0.5235988F, 0F);
      Segment_3 = new ModelRenderer(this, 9, 47);
      Segment_3.addBox(-1F, 0F, 0F, 2, 12, 2);
      Segment_3.setRotationPoint(-8F, 10F, -11F);
      Segment_3.setTextureSize(64, 64);
      Segment_3.mirror = true;
      setRotation(Segment_3, 0F, 0.6457718F, 0F);
      segment_4 = new ModelRenderer(this, 9, 47);
      segment_4.addBox(0F, 0F, -1F, 2, 12, 2);
      segment_4.setRotationPoint(8F, 10F, -8F);
      segment_4.setTextureSize(64, 64);
      segment_4.mirror = true;
      setRotation(segment_4, 0F, 0.5934119F, 0F);
      foot_3 = new ModelRenderer(this, 3, 49);
      foot_3.addBox(0F, 12F, -1.5F, 0, 2, 1);
      foot_3.setRotationPoint(-8F, 10F, -11F);
      foot_3.setTextureSize(64, 64);
      foot_3.mirror = true;
      setRotation(foot_3, 0F, -2.600541F, 0F);
      foot_4 = new ModelRenderer(this, 3, 49);
      foot_4.addBox(0F, 12F, 0.5F, 0, 2, 1);
      foot_4.setRotationPoint(8F, 10F, -8F);
      foot_4.setTextureSize(64, 64);
      foot_4.mirror = true;
      setRotation(foot_4, 0F, 2.129302F, 0F);
      arm_1 = new ModelRenderer(this, 15, 28);
      arm_1.addBox(0F, 0F, 0F, 1, 8, 1);
      arm_1.setRotationPoint(2F, 8F, -1F);
      arm_1.setTextureSize(64, 64);
      arm_1.mirror = true;
      setRotation(arm_1, 0F, 0F, -1.570796F);
      arm_2 = new ModelRenderer(this, 15, 28);
      arm_2.addBox(0F, 0F, 0F, 1, 8, 1);
      arm_2.setRotationPoint(-1F, 7F, -1F);
      arm_2.setTextureSize(64, 64);
      arm_2.mirror = true;
      setRotation(arm_2, 0F, 0F, 1.570796F);
      foot_1 = new ModelRenderer(this, 3, 49);
      foot_1.addBox(0.3F, 12F, -0.5F, 0, 2, 1);
      foot_1.setRotationPoint(-8F, 10F, 7F);
      foot_1.setTextureSize(64, 64);
      foot_1.mirror = true;
      setRotation(foot_1, 0F, -0.837758F, 0F);
      foot2 = new ModelRenderer(this, 3, 49);
      foot2.addBox(0F, 12F, 0F, 0, 2, 1);
      foot2.setRotationPoint(6.4F, 10F, 7F);
      foot2.setTextureSize(64, 64);
      foot2.mirror = true;
      setRotation(foot2, 0F, 0.4537856F, 0F);
      hand_1 = new ModelRenderer(this, 8, 31);
      hand_1.addBox(7F, 0F, -1F, 1, 2, 1);
      hand_1.setRotationPoint(2F, 8.1F, -1F);
      hand_1.setTextureSize(64, 64);
      hand_1.mirror = true;
      setRotation(hand_1, -1.570796F, 0F, 0F);
      Hand_2 = new ModelRenderer(this, 8, 31);
      Hand_2.addBox(-8F, 0F, 0.1F, 1, 2, 1);
      Hand_2.setRotationPoint(-1F, 7F, -1F);
      Hand_2.setTextureSize(64, 64);
      Hand_2.mirror = true;
      setRotation(Hand_2, -1.570796F, 0F, 0F);
      claw_1 = new ModelRenderer(this, 2, 31);
      claw_1.addBox(7.5F, 2F, -0.9F, 0, 1, 1);
      claw_1.setRotationPoint(2F, 8F, -1F);
      claw_1.setTextureSize(64, 64);
      claw_1.mirror = true;
      setRotation(claw_1, -1.570796F, 0F, 0F);
      claw_2 = new ModelRenderer(this, 2, 31);
      claw_2.addBox(-7.5F, 2F, 0.1F, 0, 1, 1);
      claw_2.setRotationPoint(-1F, 7F, -1F);
      claw_2.setTextureSize(64, 64);
      claw_2.mirror = true;
      setRotation(claw_2, -1.570796F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    //super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    head.renderWithRotation(f5);
    body.renderWithRotation(f5);
    leg3.renderWithRotation(f5);
    leg4.renderWithRotation(f5);
    leg1.renderWithRotation(f5);
    leg2.renderWithRotation(f5);
    middle.renderWithRotation(f5);
    neck.renderWithRotation(f5);
    back_of_head.renderWithRotation(f5);
    segment_1.renderWithRotation(f5);
    segment_2.renderWithRotation(f5);
    Segment_3.renderWithRotation(f5);
    segment_4.renderWithRotation(f5);
    foot_3.renderWithRotation(f5);
    foot_4.renderWithRotation(f5);
    arm_1.renderWithRotation(f5);
    arm_2.renderWithRotation(f5);
    foot_1.renderWithRotation(f5);
    foot2.renderWithRotation(f5);
    hand_1.renderWithRotation(f5);
    Hand_2.renderWithRotation(f5);
    claw_1.renderWithRotation(f5);
    claw_2.renderWithRotation(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6,Entity entity)
  {
    super.setRotationAngles(par1, par2, par3, par4, par5, par6,entity);
    this.head.rotateAngleY = -3.1415926F + par4 / (180F / (float)Math.PI);
    this.head.rotateAngleX = -par5 / (180F / (float)Math.PI);
    this.back_of_head.rotateAngleY = 3.1415926F + this.head.rotateAngleY;
    this.back_of_head.rotateAngleX = -this.head.rotateAngleX;
  }

}
