// Date: 3/23/2013 2:15:17 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package wildycraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.model.ModelSpider;
import net.minecraft.entity.Entity;

public class ModelScorpion extends ModelSpider
{
  //fields
    ModelRenderer Clawarm1;
    ModelRenderer Clawarm2;
    ModelRenderer tailsegment1;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Body;
    ModelRenderer RearEnd;
    ModelRenderer spiderLeg8;
    ModelRenderer spiderLeg7;
  
  public ModelScorpion()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      //Clawarm1.mirror = true;
      Clawarm1 = new ModelRenderer(this, 1, 49);
      Clawarm1.addBox(0F, 0F, 0F, 9, 2, 2);
      Clawarm1.setRotationPoint(11F, 16.1F, -6F);
      Clawarm1.setTextureSize(64, 64);
      //Clawarm1.mirror = true;
      setRotation(Clawarm1, 0.0349066F, 1.745329F, -0.0698132F);
      //Clawarm1.mirror = false;
      Clawarm2 = new ModelRenderer(this, 1, 49);
      Clawarm2.addBox(0F, 0F, 0F, 9, 2, 2);
      Clawarm2.setRotationPoint(-14F, 15.26667F, -6F);
      Clawarm2.setTextureSize(64, 64);
      Clawarm2.mirror = true;
      setRotation(Clawarm2, 0.0174533F, 1.623156F, 0F);
      tailsegment1 = new ModelRenderer(this, 27, 10);
      tailsegment1.addBox(0F, -2F, -2F, 14, 3, 4);
      tailsegment1.setRotationPoint(0F, 18F, 14F);
      tailsegment1.setTextureSize(64, 64);
      tailsegment1.mirror = true;
      setRotation(tailsegment1, -0.0872665F, 1.361357F, -2.216568F);
      Shape1 = new ModelRenderer(this, 30, 3);
      Shape1.addBox(0F, 0F, 0F, 14, 3, 2);
      Shape1.setRotationPoint(-0.4666667F, 9.666667F, 21F);
      Shape1.setTextureSize(64, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0.0698132F, -1.64061F, -2.478368F);
      Shape2 = new ModelRenderer(this, 38, 41);
      Shape2.addBox(0F, 0F, 0F, 10, 2, 2);
      Shape2.setRotationPoint(-2F, 0F, 11F);
      Shape2.setTextureSize(64, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 1.466077F, 0.6457718F);
      Shape3 = new ModelRenderer(this, 39, 35);
      Shape3.addBox(0F, 0F, 0F, 2, 3, 1);
      Shape3.setRotationPoint(-1F, 6F, 3F);
      Shape3.setTextureSize(64, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0.0872665F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 39, 29);
      Shape4.addBox(0F, 0F, 1F, 2, 3, 1);
      Shape4.setRotationPoint(-1F, 7F, 1F);
      Shape4.setTextureSize(64, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0.1047198F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 39, 24);
      Shape5.addBox(0F, 0F, 0F, 2, 2, 1);
      Shape5.setRotationPoint(-1F, 8F, 1F);
      Shape5.setTextureSize(64, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0.122173F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 41, 19);
      Shape6.addBox(0F, 0F, 0F, 0, 2, 1);
      Shape6.setRotationPoint(0F, 7.4F, 0F);
      Shape6.setTextureSize(64, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0.5585054F, 0.0349066F, 0F);
      Shape7 = new ModelRenderer(this, 47, 19);
      Shape7.addBox(0F, 0F, 0F, 1, 2, 7);
      Shape7.setRotationPoint(-13F, 14F, -14F);
      Shape7.setTextureSize(64, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0.1570796F, 3.01942F, 0F);
      Shape8 = new ModelRenderer(this, 47, 19);
      Shape8.addBox(0F, 0F, 0F, 1, 2, 7);
      Shape8.setRotationPoint(11.13333F, 14F, -14F);
      Shape8.setTextureSize(64, 64);
      Shape8.mirror = true;
      setRotation(Shape8, 0.1570796F, 3.152065F, 0F);
      Shape9 = new ModelRenderer(this, 47, 19);
      Shape9.addBox(0F, 0F, 0F, 1, 2, 7);
      Shape9.setRotationPoint(11F, 15F, -14F);
      Shape9.setTextureSize(64, 64);
      Shape9.mirror = true;
      setRotation(Shape9, -0.1570796F, 3.141593F, 0F);
      Shape10 = new ModelRenderer(this, 47, 19);
      Shape10.addBox(0F, 0F, 0F, 1, 2, 7);
      Shape10.setRotationPoint(-13F, 15F, -14F);
      Shape10.setTextureSize(64, 64);
      Shape10.mirror = true;
      setRotation(Shape10, -0.2443461F, -3.152065F, 0F);
      spiderHead = new ModelRenderer(this, 32, 48);
      spiderHead.addBox(-4F, -4F, -8F, 8, 8, 8);
      spiderHead.setRotationPoint(0F, 20F, -3F);
      spiderHead.setTextureSize(64, 64);
      spiderHead.mirror = true;
      setRotation(spiderHead, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(-3F, -3F, -3F, 6, 6, 6);
      Body.setRotationPoint(0F, 20F, 0F);
      Body.setTextureSize(64, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      RearEnd = new ModelRenderer(this, 0, 28);
      RearEnd.addBox(-5F, -4F, -6F, 6, 6, 12);
      RearEnd.setRotationPoint(2F, 21F, 9F);
      RearEnd.setTextureSize(64, 64);
      RearEnd.mirror = true;
      setRotation(RearEnd, 0F, 0F, 0F);
      spiderLeg8 = new ModelRenderer(this, 1, 57);
      spiderLeg8.addBox(0F, -1F, -1F, 11, 2, 2);
      spiderLeg8.setRotationPoint(4F, 19F, -2F);
      spiderLeg8.setTextureSize(64, 64);
      spiderLeg8.mirror = true;
      setRotation(spiderLeg8, 0F, 0.5585054F, -0.2094395F);
      spiderLeg6 = new ModelRenderer(this, 1, 19);
      spiderLeg6.addBox(-1F, -1F, -1F, 16, 2, 2);
      spiderLeg6.setRotationPoint(4F, 20F, 0F);
      spiderLeg6.setTextureSize(64, 64);
      spiderLeg6.mirror = true;
      setRotation(spiderLeg6, 0F, 0.2792527F, 0.1919862F);
      //Leg4.mirror = true;
      spiderLeg4 = new ModelRenderer(this, 1, 19);
      spiderLeg4.addBox(-1F, -1F, -1F, 16, 2, 2);
      spiderLeg4.setRotationPoint(4F, 20F, 4F);
      spiderLeg4.setTextureSize(64, 64);
      spiderLeg4.mirror = true;
      setRotation(spiderLeg4, 0F, -0.2617994F, 0.1919862F);
      spiderLeg4.mirror = false;
      spiderLeg2 = new ModelRenderer(this, 1, 19);
      spiderLeg2.addBox(-1F, -1F, -1F, 16, 2, 2);
      spiderLeg2.setRotationPoint(4F, 20F, 8F);
      spiderLeg2.setTextureSize(64, 64);
      spiderLeg2.mirror = true;
      setRotation(spiderLeg2, 0F, -0.5759587F, 0.1919862F);
      spiderLeg7 = new ModelRenderer(this, 1, 57);
      spiderLeg7.addBox(-15F, -1F, -1F, 11, 2, 2);
      spiderLeg7.setRotationPoint(0F, 19F, -1F);
      spiderLeg7.setTextureSize(64, 64);
      spiderLeg7.mirror = true;
      setRotation(spiderLeg7, 0.0174533F, -0.4014257F, 0.1745329F);
      spiderLeg5 = new ModelRenderer(this, 1, 19);
      spiderLeg5.addBox(-15F, -1F, -1F, 16, 2, 2);
      spiderLeg5.setRotationPoint(-4F, 20F, 0F);
      spiderLeg5.setTextureSize(64, 64);
      spiderLeg5.mirror = true;
      setRotation(spiderLeg5, 0F, -0.2792527F, -0.1919862F);
      spiderLeg3 = new ModelRenderer(this, 1, 19);
      spiderLeg3.addBox(-15F, -1F, -1F, 16, 2, 2);
      spiderLeg3.setRotationPoint(-4F, 20F, 4F);
      spiderLeg3.setTextureSize(64, 64);
      spiderLeg3.mirror = true;
      setRotation(spiderLeg3, 0F, 0.0698132F, -0.1919862F);
      spiderLeg1 = new ModelRenderer(this, 1, 19);
      spiderLeg1.addBox(-15F, -1F, -1F, 16, 2, 2);
      spiderLeg1.setRotationPoint(-4F, 20F, 8F);
      spiderLeg1.setTextureSize(64, 64);
      spiderLeg1.mirror = true;
      setRotation(spiderLeg1, 0F, 0.5759587F, -0.1919862F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    //super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    Clawarm1.render(f5);
    Clawarm2.render(f5);
    tailsegment1.renderWithRotation(f5);
    Shape1.renderWithRotation(f5);
    Shape2.renderWithRotation(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    spiderHead.render(f5);
    Body.render(f5);
    RearEnd.render(f5);
    spiderLeg8.render(f5);
    spiderLeg6.render(f5);
    spiderLeg4.render(f5);
    spiderLeg2.render(f5);
    spiderLeg7.render(f5);
    spiderLeg5.render(f5);
    spiderLeg3.render(f5);
    spiderLeg1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
