// Date: 4/11/2013 11:27:29 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package wildycraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelBeaver extends ModelBase
{
  //fields
    ModelRenderer teeth;
    ModelRenderer tail;
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer right_hind_foot;
    ModelRenderer left_hind_foot;
    ModelRenderer right_foot;
    ModelRenderer left_foot;
  
  public ModelBeaver()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      teeth = new ModelRenderer(this, 6, 12);
      teeth.addBox(-1F, 4F, -8F, 2, 1, 0);
      teeth.setRotationPoint(0F, 14F, -6F);
      teeth.setTextureSize(128, 128);
      teeth.mirror = true;
      setRotation(teeth, 0F, 0F, 0F);
      tail = new ModelRenderer(this, 53, 25);
      tail.addBox(-3F, -1F, 0F, 6, 2, 12);
      tail.setRotationPoint(0F, 17F, 9F);
      tail.setTextureSize(128, 128);
      tail.mirror = true;
      setRotation(tail, -0.418879F, 0F, 0F);
      head = new ModelRenderer(this, 14, 0);
      head.addBox(-4F, -4F, -8F, 8, 8, 8);
      head.setRotationPoint(0F, 14F, -6F);
      head.setTextureSize(128, 128);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 13, 21);
      body.addBox(-5F, -10F, -7F, 10, 16, 8);
      body.setRotationPoint(0F, 13F, 3F);
      body.setTextureSize(128, 128);
      body.mirror = true;
      setRotation(body, 1.570796F, 0F, 0F);
      leg1 = new ModelRenderer(this, 22, 47);
      leg1.addBox(-2F, 0F, -2F, 4, 6, 4);
      leg1.setRotationPoint(-3F, 18F, 7F);
      leg1.setTextureSize(128, 128);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 22, 47);
      leg2.addBox(-2F, 0F, -2F, 4, 6, 4);
      leg2.setRotationPoint(3F, 18F, 7F);
      leg2.setTextureSize(128, 128);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 22, 47);
      leg3.addBox(-2F, 0F, -2F, 4, 6, 4);
      leg3.setRotationPoint(-3F, 18F, -5F);
      leg3.setTextureSize(128, 128);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 22, 47);
      leg4.addBox(-2F, 0F, -2F, 4, 6, 4);
      leg4.setRotationPoint(3F, 18F, -5F);
      leg4.setTextureSize(128, 128);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      right_hind_foot = new ModelRenderer(this, 21, 60);
      right_hind_foot.addBox(-1F, 5F, -4F, 4, 1, 6);
      right_hind_foot.setRotationPoint(-4F, 18F, 7F);
      right_hind_foot.setTextureSize(128, 128);
      right_hind_foot.mirror = true;
      setRotation(right_hind_foot, 0F, 0F, 0F);
      left_hind_foot = new ModelRenderer(this, 21, 60);
      left_hind_foot.addBox(-2F, 5F, -4F, 4, 1, 6);
      left_hind_foot.setRotationPoint(3F, 18F, 7F);
      left_hind_foot.setTextureSize(128, 128);
      left_hind_foot.mirror = true;
      setRotation(left_hind_foot, 0F, 0F, 0F);
      right_foot = new ModelRenderer(this, 21, 60);
      right_foot.addBox(-2F, 5F, -4F, 4, 1, 6);
      right_foot.setRotationPoint(-3F, 18F, -5F);
      right_foot.setTextureSize(128, 128);
      right_foot.mirror = true;
      setRotation(right_foot, 0F, 0F, 0F);
      left_foot = new ModelRenderer(this, 21, 60);
      left_foot.addBox(-2F, 5F, -4F, 4, 1, 6);
      left_foot.setRotationPoint(3F, 18F, -5F);
      left_foot.setTextureSize(128, 128);
      left_foot.mirror = true;
      setRotation(left_foot, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
   // super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    teeth.renderWithRotation(f5);
    tail.renderWithRotation(f5);
    head.renderWithRotation(f5);
    body.renderWithRotation(f5);
    leg1.renderWithRotation(f5);
    leg2.renderWithRotation(f5);
    leg3.renderWithRotation(f5);
    leg4.renderWithRotation(f5);
    right_hind_foot.renderWithRotation(f5);
    left_hind_foot.renderWithRotation(f5);
    right_foot.renderWithRotation(f5);
    left_foot.renderWithRotation(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6,Entity entity)
  {
    super.setRotationAngles(par1,par2, par3, par4, par5, par6,entity);
    this.head.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.head.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.leg1.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
    this.leg2.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
    this.leg3.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
    this.leg4.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
    teeth.rotateAngleX = this.head.rotateAngleX;
    teeth.rotateAngleY = this.head.rotateAngleY;
    right_hind_foot.rotateAngleX = leg1.rotateAngleX;
    left_hind_foot.rotateAngleX = leg2.rotateAngleX;
    right_foot.rotateAngleX = leg3.rotateAngleX;
    left_foot.rotateAngleX = leg4.rotateAngleX;
    
  }

}
